##### input files #####

# reference genome (required)
reference: /path/to/ref.fna

# short read data (at least two samples required)
reads:
  sample1:
    [/path/to/sample1_R1.fq,
  /path/tp/sample1_R2.fq]
  sample2:
    [/path/to/sample2_R1.fq,
  /path/to/sample2_R2.fq]
  sample3: /path/to/sample3.fq

# prefix for output files (optional - can leave blank)
prefix:


##### workflow parameters #####

# alignment parameters:
mapq: 60
n_mismatches: 5

# variant calling parameters:
min_cvg: 5
min_genome_percent: 0.5
base_freq: 0.8
