name: ssift
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - bwa
  - samtools
  - ncurses
  - bamtools
  - bedtools
  - MUSCLE
  - FastTree
  - r-ggplot2
  - bioconductor-ggtree
  - r-phangorn
